kin-labs/kinetic

- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/demo/sdk/ui/src/lib/sdk-control-panel-submit-payment.tsx
- libs/sdk/src/lib/helpers/serialize-create-account-transaction.ts
- libs/sdk/src/lib/helpers/serialize-make-transfer-transaction.ts
- libs/sdk/src/lib/mogami-sdk-internal.ts
- libs/sdk/src/lib/mogami-sdk.ts
- libs/solana/src/lib/solana.spec.ts
- package.json
- yarn.lock
Closes #139 
Create Account:
https://explorer.solana.com/tx/3Eg3nsjYSyeMjJBWArHEEwawZMnd5WJ36bM2bamF7DBMzF66DKtjZiBuQN7DsBEYCnw234yLBFdvNgSiKk8CGzNU?cluster=devnet
Make Transfer:
https://explorer.solana.com/tx/ye9cHitJGtwYfzGEZQRQENs1EbCYMpeGcqT5LGSZaH8sDZ8pLs4Bt6DwLufSvK6xf1MxscSZvoiyrUChqEVhF9a?cluster=devnet
> feat: Implement memo and AppIndex for Transactions

- libs/sdk/src/lib/helpers/serialize-make-transfer-batch-transactions.ts
> fix: use correct max payment size for a Transfer Batch

- api-schema.graphql
- api-swagger.json
- apps/api-e2e/src/generated/api-sdk.ts
- apps/demo-e2e/src/integration/app.spec.ts
- graphql.schema.json
- libs/admin/app/ui/src/lib/admin-app-ui-transaction-status.tsx
- libs/admin/app/ui/src/lib/admin-app-ui-transaction-timeline.tsx
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/app/data-access/src/lib/api-app-data-access.module.ts
- libs/api/app/data-access/src/lib/api-app-transaction-data-access.service.ts
- libs/api/app/data-access/src/lib/entity/app-transaction.entity.ts
- libs/api/app/feature/src/lib/api-app-transaction-feature.resolver.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/sdk/src/generated/api.ts
- libs/sdk/src/lib/mogami-sdk-internal.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app.graphql
- libs/solana/src/lib/helpers/parse-and-sign-token-transfer.ts
- libs/solana/src/lib/helpers/parse-and-sign-transaction.ts
- libs/solana/src/lib/solana.ts
> feat: watch for finalized apps and update AppTransction

- apps/sdk-e2e/src/integration/mogami-sdk-e2e.spec.ts
> test: Add e2e request airdrop test

- apps/api/src/main.ts
- libs/api/config/data-access/src/lib/api-config-data-access.service.ts
@RamirezAlex I hope/think this will fix the issue with the new-line in `api-schema.graphql`.
> chore: format api-schema.graphql on dev server start

- api-swagger.json
- libs/api/app/data-access/src/lib/entity/app-transaction.entity.ts
> feat: Make AppTransaction fields optional

- api-swagger.json
- libs/api/account/data-access/src/lib/entities/balance-response.entity.ts
- libs/sdk/src/generated/api.ts
> fix: set the BalanceToken response type to array

- api-swagger.json
- apps/sdk-e2e/src/integration/airdrop-kinetic-sdk-e2e.spec.ts
- libs/airdrop/src/lib/airdrop.ts
- libs/api/airdrop/data-access/src/lib/api-airdrop-data-access.service.ts
- libs/api/airdrop/data-access/src/lib/dto/request-airdrop-request.dto.ts
- libs/demo/sdk/ui/src/lib/commitment-switcher.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-request-airdrop.tsx
- libs/sdk/src/generated/api.ts
- libs/sdk/src/lib/interfaces/request-airdrop-options.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
> feat: allow setting commitment on Airdrop request

- apps/sdk-e2e/src/integration/account-kinetic-sdk-e2e.spec.ts
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/demo/sdk/ui/src/lib/sdk-control-panel-account-history.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-token-accounts.tsx
- libs/sdk/src/lib/kinetic-sdk-internal.ts
> chore: Implement proper types for SDK methods

- libs/sdk/src/lib/kinetic-sdk.ts
> fix: Remove warnings in kinetic-sdk.ts

- api-swagger.json
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/account/data-access/src/lib/dto/create-account-request.dto.ts
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/api/transaction/data-access/src/lib/dto/make-transfer-request.dto.ts
- libs/sdk/src/generated/api.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
> feat: set 'tx' property type to binary string instead of Buffer

- api-swagger.json
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/app/data-access/src/lib/api-app-data-access.service.ts
- libs/api/app/data-access/src/lib/entity/app-transaction.entity.ts
- libs/api/app/feature/src/lib/api-app-transaction-feature.resolver.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/sdk/src/generated/api.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
> feat: persist duration on AppTransaction object

- libs/demo/keypair/feature/src/lib/demo-keypair-feature.tsx
- libs/demo/keypair/ui/src/lib/import-byte-array-modal.tsx
- libs/demo/keypair/ui/src/lib/import-mnemonic-modal.tsx
- libs/demo/keypair/ui/src/lib/keypair-details-modal.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-account-balance.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-account-history.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-app-config.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-create-account.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-make-payment-batch.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-make-payment.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-request-airdrop.tsx
- libs/demo/sdk/ui/src/lib/sdk-control-panel-token-accounts.tsx
- libs/demo/server/ui/src/lib/server-create-modal.tsx
- libs/demo/server/ui/src/lib/server-details-modal.tsx
- libs/demo/server/ui/src/lib/server-grid.tsx
Some minor cleanup of leftovers from our demo-e2e test.
> refactor: remove classnames that were used for e2e tests

- api-schema.graphql
- api-swagger.json
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/app/data-access/src/lib/entity/app-transaction-error.entity.ts
- libs/api/app/data-access/src/lib/helpers/parse-error.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/sdk/src/generated/api.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql
> feat: Include logs in AppTransactionError model

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/app/feature/src/lib/api-app-feature.module.ts
- libs/api/app/feature/src/lib/api-app-feature.resolver.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql
Adds the property `defaultEnvUrl` and `settingsUrl` to the GraphQL `App` object to reduce the logic on the frontend.
> feat: add dynamic fields to improve Admin UI flow

- api-schema.graphql
- api-swagger.json
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
> feat: add cron job to mark transactions as expired

- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/sdk/src/generated/api.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
Some auto-generated code that should have been added with #355 and #354
> chore: update auto-generated code

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- apps/api-e2e/src/integration/app-feature-resolver.spec.ts
- graphql.schema.json
- libs/admin/app/feature/src/lib/admin-app-user-env-settings-tab.tsx
- libs/admin/app/ui/src/index.ts
- libs/admin/app/ui/src/lib/admin-app-ui-app-env-allowed-ips-form.tsx
- libs/api/app/data-access/src/lib/entity/app-env.entity.ts
- libs/api/app/feature/src/lib/api-app-env-feature.resolver.ts
- libs/api/core/data-access/src/lib/api-core-data-access.service.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/api/transaction/feature/src/lib/api-transaction-feature.controller.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql
- libs/shared/util/admin-sdk/src/graphql/feature-app-user.graphql
This is a follow up PR for #357
> feat: Implement SDK filter for IPs follow up -#357 (ipsAllowed)

- apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
> feat: Return proper error destination account doesn't exist.

- api-schema.graphql
- api-swagger.json
- apps/api-e2e/src/generated/api-sdk.ts
- apps/api-e2e/src/integration/app-feature-resolver.spec.ts
- graphql.schema.json
- libs/admin/app/feature/src/lib/admin-app-user-env-settings-tab.tsx
- libs/admin/app/ui/src/index.ts
- libs/admin/app/ui/src/lib/admin-app-ui-app-env-allowed-ua-form.tsx
- libs/admin/app/ui/src/lib/admin-app-ui-app-env-blocked-ua-form.tsx
- libs/admin/app/ui/src/lib/admin-app-ui-transactions.tsx
- libs/api/app/data-access/src/lib/entity/app-env.entity.ts
- libs/api/app/data-access/src/lib/entity/app-transaction.entity.ts
- libs/api/app/feature/src/lib/api-app-env-feature.resolver.ts
- libs/api/core/data-access/src/lib/api-core-data-access.service.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/sdk/src/generated/api.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql
- libs/shared/util/admin-sdk/src/graphql/feature-app-user.graphql
> feat: Implement SDK filter for User Agents

- apps/api-e2e/src/generated/api-sdk.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-user.graphql
Fix for improving DX in kinetic-manager project.
> fix: add counter to Kinetic Admin SDK queries

- libs/demo/sdk/ui/src/lib/sdk-control-panel.tsx
- libs/keypair/project.json
- libs/keypair/src/index.ts
- libs/keypair/src/version.ts
- libs/sdk/project.json
- libs/sdk/src/index.ts
- libs/sdk/src/lib/kinetic-sdk.ts
- libs/sdk/src/version.ts
- libs/solana/project.json
- libs/solana/src/index.ts
- libs/solana/src/lib/solana.ts
- libs/solana/src/version.ts
- package.json
- tools/update-version.js
> build: tag package versions on build

- apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
> feat: Add a check that disallows sending tokens to any of the mints

- .github/workflows/test-api-e2e.yml
- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- apps/api-e2e/src/integration/app-feature-resolver.spec.ts
- graphql.schema.json
- libs/admin/app/feature/src/lib/admin-app-user-env-settings-tab.tsx
- libs/admin/app/ui/src/lib/admin-app-ui-app-env-webhook-form.tsx
- libs/api/app/data-access/src/lib/dto/user-app-env-update.input.ts
- libs/api/app/data-access/src/lib/entity/app-env.entity.ts
- libs/api/config/data-access/src/lib/api-config-data-access.service.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/wallet/data-access/src/lib/api-wallet-data-access.module.ts
- libs/api/wallet/data-access/src/lib/api-wallet-data-access.service.spec.ts
- libs/api/wallet/data-access/src/lib/api-wallet-user-data-access.service.ts
- libs/api/webhook/data-access/src/lib/api-webhook-data-access.service.ts
- libs/shared/util/admin-sdk/src/generated/graphql.tsx
- libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql
> feat: Add notifications if app wallet reaches a certain threshold

- libs/solana/src/lib/helpers/generate-make-transfer-batch-transaction.ts
- libs/solana/src/lib/helpers/generate-make-transfer-transaction.ts
- libs/solana/src/lib/helpers/parse-and-sign-token-transfer.ts
> feat: Move from transferInstruction to transferCheckedInstruction

- api-swagger.json
- apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/account/data-access/src/lib/entities/balance-response.entity.ts
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/sdk/src/generated/api.ts
- libs/solana/src/lib/helpers/parse-and-sign-token-transfer.ts
- libs/solana/src/lib/interfaces/balance-mint.ts
- libs/solana/src/lib/interfaces/balance-summary.ts
- libs/solana/src/lib/interfaces/balance-token.ts
- libs/solana/src/lib/interfaces/index.ts
- libs/solana/src/lib/solana.spec.ts
- libs/solana/src/lib/solana.ts
> feat: make BalanceResponse return values formatted with decimals

- api-swagger.json
- libs/api/account/data-access/src/lib/entities/balance-response.entity.ts
This fixes an issue with the code generation in the Kinetic Dart SDK
> fix: give BalanceToken decimals field a dedfault value

- apps/api-e2e/src/generated/api-sdk.ts
- libs/web/util/sdk/src/codegen.yml
Accidentally deleted [here](https://github.com/kin-labs/kinetic/commit/e2f8df5d930a5862c1c478837e462910f82d9ff1#diff-ff2ea1f5f70de0024678dee3f0fb815a7d65743f69032df2e14901804d03491cL5-L13).
> fix: add back deleted codegen config for api-e2e sdk

- libs/solana/src/lib/solana.ts
> Add { skipPreflight: false } flag to sendTransaction 

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/cluster/data-access/src/lib/api-cluster-admin-data-access.service.ts
- libs/api/cluster/feature/src/lib/api-cluster-admin-feature.resolver.ts
- libs/api/cluster/feature/src/lib/api-cluster-mint-feature.resolver.ts
- libs/api/wallet/data-access/src/lib/api-wallet-user-data-access.service.ts
- libs/api/wallet/feature/src/lib/api-wallet-user-feature.resolver.ts
- libs/keypair/src/lib/keypair.spec.ts
- libs/keypair/src/lib/keypair.ts
- libs/web/admin/feature/src/lib/cluster/web-admin-feature-cluster-mints-tab.tsx
- libs/web/admin/ui/src/lib/web-admin-ui-mint-details.tsx
- libs/web/admin/ui/src/lib/web-admin-ui-mints.tsx
- libs/web/app/feature/src/lib/web-app-env-wallets-tab.tsx
- libs/web/util/sdk/src/generated/graphql.tsx
- libs/web/util/sdk/src/graphql/feature-cluster.graphql
- libs/web/util/sdk/src/graphql/feature-wallet.graphql
> feat: allow importing wallets using mnemonic, secret key and byte array

- api-swagger.json
- libs/api/account/data-access/src/lib/entities/confirmed-signature-info.entity.ts
- libs/api/transaction/data-access/src/lib/entities/compiled-inner-instruction.entity.ts
- libs/api/transaction/data-access/src/lib/entities/compiled-instruction.entity.ts
- libs/api/transaction/data-access/src/lib/entities/confirmed-transaction-meta.entity.ts
- libs/api/transaction/data-access/src/lib/entities/context.entity.ts
- libs/api/transaction/data-access/src/lib/entities/minimum-rent-exemption-balance-response.entity.ts
- libs/api/transaction/data-access/src/lib/entities/signature-status.entity.ts
- libs/api/transaction/data-access/src/lib/entities/token-amount.entity.ts
- libs/api/transaction/data-access/src/lib/entities/token-balance.entity.ts
- libs/api/transaction/data-access/src/lib/entities/transaction-response.entity.ts
- libs/api/transaction/data-access/src/lib/entities/transaction.entity.ts
- libs/sdk/src/generated/api.ts
> fix: properly type OpenApi models around ConfirmTransactionMeta

- libs/web/app/feature/src/lib/web-app-env-wallet-tab.tsx
- libs/web/app/feature/src/lib/web-app-env-wallets-tab.tsx
- libs/web/app/feature/src/lib/web-transaction-detail.tsx
- libs/web/app/ui/src/lib/web-app-ui-app-env-summary.tsx
- libs/web/app/ui/src/lib/web-app-ui-wallet.tsx
Adds an option to remove a wallet from the environment, some links to the Solana Explorer and more info to the Transaction details page.
> feat: add option to remove wallet from environment 

- libs/web/app/feature/src/lib/web-app-env-wallets-tab.tsx
- libs/web/app/ui/src/lib/web-app-ui-wallet.tsx
- libs/web/toolbox/ui/src/index.ts
- libs/web/toolbox/ui/src/lib/web-toolbox-ui.tsx
Based on feedback from the ecosystem partners, we have added an easier way to send out airdrops to dev wallets.
> feat: add Airdrop option for Mints to Wallets screen

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/app/data-access/src/lib/api-app-env-user-data-access.service.ts
- libs/api/app/feature/src/lib/api-app-env-user-feature.resolver.ts
- libs/web/app/feature/src/lib/web-app-env-dashboard-tab.tsx
- libs/web/app/feature/src/lib/web-app-env-settings-access.tsx
- libs/web/app/feature/src/lib/web-app-env-settings-maintenance.tsx
- libs/web/app/feature/src/lib/web-app-env-settings-mints.tsx
- libs/web/app/feature/src/lib/web-app-env-settings.tsx
- libs/web/util/sdk/src/generated/graphql.tsx
- libs/web/util/sdk/src/graphql/feature-app-user.graphql
This adds a simple option to purge all the transactions and related records from an environment.
We can later extend this feature by allow people to purge based on date range or set up automatic purging.
> feat: add option to purge transactions for an environment

- libs/api/queue/data-access/src/lib/entity/queue-type.enum.ts
- libs/api/queue/data-access/src/lib/queue/close-account/api-queue-close-account.processor.ts
- libs/api/queue/data-access/src/lib/queue/close-account/api-queue-close-account.service.ts
A few tweaks to improving typing for the queue that got added in #506
> refactor: improving typing on QueueOptions

- api-swagger.json
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/account/feature/src/lib/api-account-feature.controller.ts
- libs/sdk/src/generated/api.ts
- libs/sdk/src/lib/interfaces/get-balance-options.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
- libs/solana/src/lib/solana.ts
This PR adds the option to fetch token account balance with a certain commitment.
> feat: allow setting commitment on getBalance

- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
> fix: improve webhook error handling

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/app/data-access/src/lib/api-app-user-data-access.service.ts
- libs/api/app/data-access/src/lib/dto/user-app-env-update.input.ts
- libs/api/app/data-access/src/lib/entity/app-env.entity.ts
- libs/api/core/data-access/src/prisma/schema.prisma
- libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts
- libs/solana/src/lib/solana.ts
- libs/web/app/feature/src/lib/web-app-env-settings-maintenance.tsx
- libs/web/app/feature/src/lib/web-app-env-settings-solana.tsx
- libs/web/app/feature/src/lib/web-app-env-settings.tsx
- libs/web/util/sdk/src/generated/graphql.tsx
- libs/web/util/sdk/src/graphql/feature-app-fragments.graphql
Builds on #532, stores the value in the DB and adds the config UI.
> feat: add configuration options for setting maxRetries and skipPreflight on Solana transactions

- api-swagger.json
- apps/sdk-e2e/src/integration/account-kinetic-sdk-e2e.spec.ts
- libs/api/account/data-access/src/lib/api-account-data-access.service.ts
- libs/api/account/feature/src/lib/api-account-feature.controller.ts
- libs/api/queue/data-access/src/lib/queue/close-account/api-queue-close-account.processor.ts
- libs/sdk/src/generated/api.ts
- libs/sdk/src/lib/interfaces/get-account-info-options.ts
- libs/sdk/src/lib/kinetic-sdk-internal.ts
This option is needed for #507
> feat: add mint parameter to getAccountInfo method

- libs/api/core/util/src/lib/get-parse-app-key.spec.ts
- libs/api/core/util/src/lib/get-parse-app-key.ts
> fix: support environments with a dash in their name

- api-schema.graphql
- apps/api-e2e/src/generated/api-sdk.ts
- graphql.schema.json
- libs/api/core/data-access/src/index.ts
- libs/api/core/data-access/src/lib/api-core.service.ts
- libs/api/core/data-access/src/lib/entities/migration-status.entity.ts
- libs/api/core/data-access/src/lib/entities/migration.entity.ts
- libs/api/core/feature/src/lib/api-core-feature.resolver.ts
- libs/api/transaction/data-access/src/lib/api-transaction.service.ts
- libs/api/wallet/data-access/src/lib/api-wallet-user.service.ts
- libs/web/admin/feature/src/lib/migration/web-admin-feature-migration-list.tsx
- libs/web/admin/feature/src/lib/migration/web-admin-feature-migration.tsx
- libs/web/admin/feature/src/lib/web-admin-feature.tsx
- libs/web/ui/layout/src/lib/web-ui-layout-header.tsx
- libs/web/util/sdk/src/generated/graphql.tsx
- libs/web/util/sdk/src/graphql/feature-core.graphql
This PR adds a section to the Admin UI where data migrations can be triggered.
> feat: add Migration section in admin to manually trigger data migrations
