kin-labs/kinetic

libs/keypair/project.json, libs/sdk/project.json, libs/solana/project.json
[Currently](https://unpkg.com/browse/@mogami/sdk@1.0.0-beta.1/package.json), the dependencies of our libraries are added to the `peerDependencies`, making installation harder than needed as we need to list all of the dependencies as installation instructions.
With this patch, they will be added to the `dependencies` object which will make the installation and instructions easier.
=> fix: make sure library deps are defined as 'dependencies' in package.json

libs/admin/app/feature/src/lib/admin-app-feature-detail.tsx, libs/admin/app/feature/src/lib/admin-app-feature.tsx, libs/admin/app/feature/src/lib/env-detail-layout.tsx, libs/admin/cluster/feature/src/lib/admin-cluster-feature-detail.tsx, libs/admin/cluster/feature/src/lib/admin-cluster-feature.tsx, libs/admin/cluster/ui/src/lib/admin-cluster-ui-form.tsx, libs/admin/ui/tabs/.babelrc, libs/admin/ui/tabs/.eslintrc.json, libs/admin/ui/tabs/README.md, libs/admin/ui/tabs/jest.config.ts, libs/admin/ui/tabs/project.json, libs/admin/ui/tabs/src/index.ts, libs/admin/ui/tabs/src/lib/admin-ui-tabs.spec.tsx, libs/admin/ui/tabs/src/lib/admin-ui-tabs.tsx, libs/admin/ui/tabs/tsconfig.json, libs/admin/ui/tabs/tsconfig.lib.json, libs/admin/ui/tabs/tsconfig.spec.json, libs/admin/user/feature/src/lib/admin-user-feature-detail.tsx, tsconfig.base.json, workspace.json
This PR adds the `AdminUiTabs` component for easy use of tabbed routes:
```tsx
function Cmp() {
const { path, url } = useRouteMatch()
const tabs = [
{ path: `${url}/environments`, label: 'Environments' },
{ path: `${url}/settings`, label: 'Settings' },
]
return <Switch>
<Route path={path} exact render={() => <Redirect to={`${url}/environments`} />} />
<Route
path={`${path}/environments`}
render={() => (
<AdminUiTabs tabs={tabs}>
<AppEnvironmentsTab appId={appId} />
</AdminUiTabs>
)}
/>
<Route
path={`${path}/settings`}
render={() => (
<AdminUiTabs tabs={tabs}>
<AdminAppUiForm app={data?.item} onSubmit={onSubmit} />
</AdminUiTabs>
)}
/>
</Switch>
}
```
=> feat: add admin ui tabs component for routed tabs

Dockerfile
```
2022-06-25T16:45:06.220363+00:00 app[web.1]: yarn run v1.22.18
2022-06-25T16:45:06.248357+00:00 app[web.1]: $ yarn prisma db push && node dist/apps/api/main.js
2022-06-25T16:45:06.746253+00:00 app[web.1]: $ /workspace/node_modules/.bin/prisma db push
2022-06-25T16:45:08.093275+00:00 app[web.1]: Error: Provided schema path `libs/api/core/data-access/src/prisma/schema.prisma` from `package.json` doesn't exist.
2022-06-25T16:45:08.109298+00:00 app[web.1]: error Command failed with exit code 1.
2022-06-25T16:45:08.109415+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-06-25T16:45:08.130670+00:00 app[web.1]: error Command failed with exit code 1.
2022-06-25T16:45:08.130772+00:00 app[web.1]: info Visit …
```
=> fix: docker container can't start because prisma file is not found

libs/sdk/src/lib/helpers/parse-kinetic-sdk-config.spec.ts, libs/sdk/src/lib/helpers/parse-kinetic-sdk-config.ts
This patch fixes an issue with the SDK not initializing when using an endpoint that ends with a slash.
=> fix: remove trailing slash for custom endpoint

.github/workflows/build-publish-docker.yml
We don't need to create images on PR as they count to our usage and they need manual cleanup. 
If we want to test an image of a PR we can always manually push it up.
=> chore: only build Docker container on dev and main branches

libs/sdk/src/lib/helpers/index.ts, libs/sdk/src/lib/helpers/kin-to-quarks.spec.ts, libs/sdk/src/lib/helpers/kin-to-quarks.ts, libs/sdk/src/lib/helpers/serialize-make-transfer-batch-transactions.ts, libs/sdk/src/lib/helpers/serialize-make-transfer-transaction.ts, libs/solana/src/lib/helpers/add-remove-decimals.spec.ts, libs/solana/src/lib/helpers/add-remove-decimals.ts, libs/solana/src/lib/helpers/index.ts
This PR changes how the `kinToQuarks` / `quarksToKin` and the underlying tools work.
- `addDecimals` / `removeDecimals` are moved to `@kin-kinetic/solana` as we need them there in a follow-up PR.
- `kinToQuarks` / `quarksToKin` are now exported from `@kin-kinetic/sdk` has higher-level utilities, basically currying the above functions with `5` decimals. This also ensures compatibility with the ecosystem that depends on these helpers.
I also migrated the tests from the `kin-node` sdk.
=> refactor: organize addDecimals, kinToQuarks, etc and add tests

libs/sdk/src/lib/kinetic-sdk-internal.ts, libs/solana/src/lib/helpers/parse-and-sign-token-transfer.ts, libs/solana/src/lib/helpers/serialize-create-account-transaction.ts, libs/solana/src/lib/helpers/serialize-make-transfer-batch-transactions.ts, libs/solana/src/lib/helpers/serialize-make-transfer-transaction.ts
We were using the [deprecated](https://github.com/solana-labs/solana/blob/627d91fb20272afa5ce790fbec01b40a29fb9852/web3.js/src/transaction.ts#L134) way to create the `Transaction`, we are now using the correct way. 
~~This also means we don't need to provide `lastValidBlockHeight` as a separate property on the `makeTransfer` endpoint. Instead, we can read it by parsing the incoming transaction.~~
Edit: it turns out `lastValidBlockHeight` is not serialized on the `Transaction` so we will still send it as a separate property to the `makeTransfer` endpoint.
=> refactor: provide lastValidBlockHeight with the transaction

package.json, yarn.lock
This makes sure we have only 1 single version of `@solana/web3.js` in the project.
=> chore: pin @solana/web3.js version

apps/api/src/main.ts, libs/api/config/data-access/src/lib/api-config-data-access.service.ts, libs/api/core/feature/src/lib/api-core-feature.module.ts
There were issues connecting the Kinetic Manager to the Devnet endpoint because of CORS configuration.
This PR fixes that.
=> feat: configure GraphQL CORS settings

.env.example, apps/api/src/main.ts, libs/api/config/data-access/src/lib/api-config-data-access.service.ts, libs/api/config/feature/src/lib/config/configuration.ts, libs/api/config/feature/src/lib/config/validation-schema.ts, libs/api/core/feature/src/lib/api-core-feature.controller.ts, libs/api/core/util/src/lib/open-telemetry-sdk.ts
This feature is needed so we can toggle how the Prometheus metrics are exposed:
- `METRICS_PORT=9000` opens a port with a `/metrics` endpoint
- `METRICS_ENDPOINT_ENABLED=true` enabled the `/api/metrics` endpoint on the API
=> feat: add env var to enable Prometheus port

apps/api/src/main.ts
Fixes this error when setting `CORS_ORIGINS` to `*`.
```
2022-09-03T16:10:51.720125+00:00 app[web.1]: [Nest] 25  - 09/03/2022, 4:10:51 PM   ERROR TypeError: _a.join is not a function
2022-09-03T16:10:51.721646+00:00 app[web.1]: TypeError: _a.join is not a function
2022-09-03T16:10:51.721647+00:00 app[web.1]: at /workspace/dist/apps/api/main.js:1:309887
2022-09-03T16:10:51.721647+00:00 app[web.1]: at Generator.next (<anonymous>)
2022-09-03T16:10:51.721648+00:00 app[web.1]: at fulfilled (/workspace/node_modules/tslib/tslib.js:115:62)
2022-09-03T16:10:51.721648+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
=> fix: make cors origin work with '*'

libs/keypair/src/lib/keypair-polyfills.ts
This polyfill is needed in both the `keypair` and `sdk` packages, so the `keypair` package can be used standalone.
=> fix: add Buffer polyfill to Keypair class

apps/api/project.json
A recent update broke running the API in Production mode, with the following error:
```
Error: Schema must contain uniquely named types but contains multiple types named "o".
at new GraphQLSchema (/Users/beeman/kin/kin-labs/kinetic/node_modules/graphql/type/schema.js:219:15)
at GraphQLSchemaFactory.create (/Users/beeman/kin/kin-labs/kinetic/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:40:24)
at GraphQLSchemaBuilder.generateSchema (/Users/beeman/kin/kin-labs/kinetic/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:35:52)
at GraphQLSchemaBuilder.build (/Users/beeman/kin/kin-labs/kinetic/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:22:31)
at GraphQLFactory.mergeWithSchema (/Users/beeman/kin/kin-labs/kinetic/node_modules/@nestjs/graphql/d …
```
=> fix: disable optimization for API as a workaround for GraphQL schema error

libs/api/cluster/data-access/src/lib/api-cluster-admin-data-access.service.ts, libs/api/config/data-access/src/lib/api-config-data-access.service.ts, libs/api/core/data-access/src/lib/api-core-data-access.service.ts, libs/web/admin/feature/src/lib/cluster/web-admin-feature-cluster-detail.tsx
Fixes #467 
@RamirezAlex in this PR we change how Clusters/Mints are provisioned, making it so that they are only created but never update. The result of this is that it will make the local development workflow a bit different. If we want to change a cluster endpoint while our local setup, we will either have to use the admin and configure it there or use ENV Vars and reset the database.
=> Fix behavior with updating Cluster endpoints

libs/api/config/data-access/src/lib/api-config-data-access.service.ts
Several people reported issues with logging in, it turns out the cookie was not set correctly. See the error in the screenshot.
This PR fixes that.
=> fix: allow setting cookies over http connections

.env.example, libs/api/config/feature/src/lib/config/configuration.ts, libs/api/config/feature/src/lib/config/validation-schema.ts
The `WEB_URL` property only needs to be set on a development setup, or when running the web UI separate from the API. On a typical production setup it will be the same as the `API_URL` with the `/api` suffix stripped off.
=> feat: infer WEB_URL from API_URL

libs/api/config/feature/src/lib/config/configuration.ts, libs/api/config/feature/src/lib/config/validation-schema.ts
With this patch, the `COOKIE_DOMAINS` property becomes optional and the default value will be set to the `hostname` part of the `API_URL` property, which should be the right value for most typical setups.
=> feat: infer COOKIE_DOMAINS default value from API_URL

.env.example, .github/workflows/test-api-e2e.yml, .github/workflows/test-sdk-e2e.yml, .github/workflows/test-web-e2e.yml, libs/api/config/feature/src/lib/config/configuration.ts, libs/api/config/feature/src/lib/config/validation-schema.ts
With this patch, we no longer need to set `CORS_BYPASS`. Instead, we will assume that CORS can be bypassed when no explicit `CORS_ORIGINS` are set. All this to make configuration simpler and have better defaults.
=> feat: infer bypassing CORS from lack of CORS_ORIGINS values

libs/keypair/src/lib/keypair.fixture.ts, libs/keypair/src/lib/keypair.spec.ts, libs/keypair/src/lib/keypair.ts
The `Keypair` class featured a method `Keypair.fromMnemonicSeed()` that used `bip39` derivation. Those mnemonics are compatible with the ones created by `solana-keygen` (`solana-keygen new --no-bip39-passphrase --no-outfile`) but are not compatible with the rest of the ecosystem, who is using `bip44` to derive the keypairs.
To avoid any confusion, we will remove the `bip39` derivation from any of our SDKs, making the only available option the one that's compatible with the larger Solana ecosystem. 
If you ever need this, it's pretty simple to implement so it doesn't seem to be a big loss to not ship this on `Keypair`.
```ts
import * as bip39 from '@scure/bip39'
function fromMnemonicSeed(mnemonic: string): Keypair {
const seed = bip39.mnemonicToSeedSync(mnemonic, '')
return …
```
=> refactor: remove bip39 mnemonic derivation (Keypair.fromMnemonicSeed)

libs/web/util/sdk/src/codegen.yml
Got this error after updating to Node 18:
```
Failed to load schema from http://localhost:3000/graphql:
fetch failed
TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11118:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async UrlLoader.load (/Users/beeman/kin/kin-labs/kinetic/node_modules/@graphql-tools/url-loader/cjs/index.js:562:29)
at async /Users/beeman/kin/kin-labs/kinetic/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
```
[The fix](https://github.com/dotansimha/graphql-code-generator/issues/7396#issuecomment-1070318950) seems to be pointing it to 127.0.0.1.
=> fix: point codegen.yml to http://127.0.0.1:3000/graphql

libs/sdk/src/lib/kinetic-sdk-internal.ts, libs/sdk/src/lib/kinetic-sdk.ts
Currently the SDK swallows error messages because it used `async`/`await` without try/catch. This patch moves it to a normal promise chain, the errors now propagate as desired:
=> fix: make sure SDK doesn't swallow connectiong error messages

apps/sdk-e2e/src/integration/account-kinetic-sdk-e2e.spec.ts, apps/sdk-e2e/src/integration/airdrop-kinetic-sdk-e2e.spec.ts, apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts, libs/api/airdrop/data-access/src/lib/api-airdrop-data-access.service.ts, libs/api/airdrop/util/src/lib/airdrop.ts, libs/api/core/util/src/lib/public-key.pipe.ts, libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts, libs/sdk/src/lib/kinetic-sdk-internal.ts
This patch fixes the issue that the SDK currently returns the raw Axios response object with the errors hidden deep inside. Instead, errors now return a string with the error message or 'Unknown error'.
=> fix: make KineticSdk throw clean error messages instead of response object

libs/api/account/data-access/src/lib/api-account-data-access.service.ts, libs/api/account/feature/src/lib/api-account-feature.controller.ts, libs/api/airdrop/data-access/src/lib/api-airdrop-data-access.service.ts, libs/api/app/data-access/src/lib/api-app-data-access.service.ts, libs/api/app/data-access/src/lib/api-app-env-user-data-access.service.ts, libs/api/app/feature/src/lib/api-app-env-user-feature.resolver.ts, libs/api/app/feature/src/lib/api-app-feature.controller.ts, libs/api/cluster/data-access/src/lib/api-cluster-admin-data-access.service.ts, libs/api/core/data-access/src/lib/api-core-data-access.service.ts, libs/api/core/util/src/index.ts, libs/api/core/util/src/lib/get-parse-app-key.ts, libs/api/queue/data-access/src/lib/api-queue-data-access.service.ts, libs/api/queue/data-access/src/lib/queue/close-account/api-queue-close-account.processor.ts, libs/api/solana/data-access/src/lib/api-solana-data-access.service.ts, libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts, libs/api/transaction/feature/src/lib/api-transaction-feature.controller.ts, libs/api/wallet/data-access/src/lib/api-wallet-user-data-access.service.ts, libs/api/webhook/data-access/src/lib/api-webhook-data-access.service.ts, libs/api/webhook/feature/src/lib/api-webhook-feature.controller.ts
This PR refactors the usage of 2 parameters (`environment: string` + `index: number`) to identify an app, to a composite key: `app-${environment}-${index}` and adds some helper functions to do this conversion.
At first glance it seems like a minor thing, but it makes things like caching easier (like in `ApiSolanaDataAccessService`) and will make #419 easier to implement.
=> refactor: use 'appKey' instead of 'environment, index' as app environment identifier

.env.example, libs/api/config/data-access/src/lib/api-config-data-access.service.ts, libs/api/config/feature/src/lib/config/configuration.ts, libs/api/config/feature/src/lib/config/validation-schema.ts, libs/api/solana/data-access/src/lib/api-solana-data-access.service.ts, libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts, libs/web/app/feature/src/lib/web-transaction-detail.tsx
This PR adds a configurable cache to the `getLatestBlockhash` method. It can be configured using the `CACHE_SOLANA_GET_LATEST_BLOCKHASH_TTL` env var and it defaults to `5` seconds. According to [this documentation](https://docs.solana.com/implemented-proposals/durable-tx-nonces#problem) it could be valid up to 2 minutes.
=> feat: add cache to solana.getLatestBlockhash method

.env.example, api-schema.graphql, apps/api-e2e/src/generated/api-sdk.ts, graphql.schema.json, libs/api/app/data-access/src/lib/api-app-admin-data-access.service.ts, libs/api/app/data-access/src/lib/dto/admin-app-create.input.ts, libs/api/config/data-access/src/lib/entity/provisioned-app.entity.ts, libs/api/config/data-access/src/lib/helpers/get-provisioned-apps.ts, libs/web/util/sdk/src/generated/graphql.tsx
This PR adds support for an optional environment variable that can be used to provision your app. I will set up the webhooks in debug mode.
For most apps this won't be super useful, but we need it so we can set this up in our CI environment and run tests against it.
=> feat: add APP_1_ENABLE_WEBHOOKS env var to provision webhooks in debug mode

libs/sdk/src/index.ts, libs/sdk/src/lib/helpers/validate-kinetic-sdk-config.ts, libs/sdk/src/lib/interfaces/close-account-options.ts, libs/sdk/src/lib/interfaces/create-account-options.ts, libs/sdk/src/lib/interfaces/get-account-info-options.ts, libs/sdk/src/lib/interfaces/get-balance-options.ts, libs/sdk/src/lib/interfaces/kinetic-sdk-config.ts, libs/sdk/src/lib/interfaces/make-transfer-options.ts, libs/sdk/src/lib/interfaces/request-airdrop-options.ts, libs/sdk/src/lib/kinetic-sdk-internal.ts, libs/sdk/src/lib/kinetic-sdk.spec.ts
This PR adds the `commitment` property to the `KineticSdkConfig` interface that can be used to set the default commitment for the SDK.
The default commitment for all operations is now `Confirmed`.
=> feat: allow setting default commitment with KineticSdk config

libs/web/admin/ui/src/lib/web-admin-ui-wallet-table.tsx, libs/web/app/ui/src/lib/web-app-ui-wallet.tsx
This fixes an issue where low balances like `0.009...` were displayed as `0`
=> fix: make sure to correctly show balance in Wallet screen

apps/sdk-e2e/src/integration/account-kinetic-sdk-e2e.spec.ts, apps/sdk-e2e/src/integration/transaction-kinetic-sdk-e2e.spec.ts, libs/sdk/src/lib/helpers/get-token-address.ts, libs/sdk/src/lib/helpers/index.ts, libs/sdk/src/lib/kinetic-sdk-internal.ts, libs/solana/src/lib/helpers/generate-make-transfer-transaction.ts, libs/solana/src/lib/interfaces/generate-make-transfer-transaction-options.ts
This PR changes how `makeTransfer` fetches the addresses of the token accounts for both the owner and destination.
Previously, it used `getAssociatedTokenAddress` combined with the `mint` and `public key`, but this does not work with token accounts that are created using and older method (eg. Agora wallets).
In this setup, we fetch the account info for both the owner and destination and it will give back and array of token accounts, regardless of how they were created. 
The logic goes like this:
- If the owners token account is not found, it fails. 
- If the destination token account is not found, and `senderCreate` is not set, it fails.
- If the destination token account is not found, and `senderCreate` is set, it will use `getAssociatedTokenAddress` to derive the address.
Part of #507.
=> refactor: use getAccountInfo to fetch token accounts on makeTransfer

libs/keypair/src/lib/keypair.ts
This method is really an implementation detail of this SDK, we don't need to expose it.
=> fix: make Keypair.fromSeed() private

libs/api/kinetic/data-access/src/lib/api-kinetic.service.ts
This patch fixes an issue where we could not send Kin from self-referencing accounts (token accounts that have the same public key as the account owner), like [this one](https://solscan.io/account/Don8L4DTVrUrRAcVTsFoCRqei5Mokde3CV3K9Ut4nAGZ).
=> fix: support the case where token account and account owner are the same

libs/web/app/feature/src/lib/web-app-env-settings-solana.tsx
This patch fixes the issue that would mark the Max Retries field as diabled if solanaTransactionMaxRetries was set to 0.
=> fix: the Max Retries input field should never be disabled

apps/sdk-e2e/src/integration/account-kinetic-sdk-e2e.spec.ts, libs/api/account/data-access/src/lib/api-account.service.ts, libs/api/kinetic/data-access/src/lib/api-kinetic.service.ts, libs/solana/src/lib/solana.spec.ts, libs/solana/src/lib/solana.ts
This patches fixes an issue introduced in #567 leading to an error 500 when checking `getBalance` on an empty account.
=> fix: make sure getBalance works with empty accounts

api-swagger.json, libs/api/account/data-access/src/lib/api-account.service.ts, libs/api/account/data-access/src/lib/dto/create-account-request.dto.ts, libs/api/core/util/src/index.ts, libs/api/core/util/src/lib/create-reference.ts, libs/api/core/util/src/lib/public-key.pipe.ts, libs/api/kinetic/data-access/src/lib/api-kinetic.service.ts, libs/api/kinetic/data-access/src/lib/dto/close-account-request.dto.ts, libs/api/transaction/data-access/src/lib/dto/make-transfer-request.dto.ts, libs/sdk/src/generated/api.ts
This patch makes sure that Kinetic API v1.0.0-rc.17 is compatible with previous SDKs in terms of the `referenceId` and `referenceType` fields.
=> fix: add compatibility for referenceId and referenceType fields
